### ISSUE TITLE
content_for kpop doesn't load scrim

### ISSUE THREAD

**Issue by AlanCornthwaiteKatalyst** [katalyst/kpop#17]
When rendering an inline modal using `content_for(:kpop)` the scrim doesn't show.

Scrim controller is loading after kpop is already loaded, so although the scrim:show event is fired, the scrim controller is not yet listening so its show method never gets called.

**Workaround**
Instead of loading kpop via content_for tags load a stimulus controller with the kpop path value(set src in the kpop tag), so that once the stimulus controller is attached to DOM, we can load the kpop content.

**Comment by sfnelson** [comment]
Verified that this has been fixed in the latest version (e.g. fringe performance modal on event page).
